### ISSUE TITLE
分组显示不全

### ISSUE THREAD

**Issue by reov** [hi94740/bilibili-timeline-filter.user.js#1]
有分类癖好
脚本只会显示一行8个分组

**Comment by hi94740** [comment]
> 有分类癖好
> 
> 脚本只会显示一行8个分组

你好，感谢反馈。可以点击最右侧的分组，会自动滚动。我知道这不是最佳解决方案，在未来我可能会替换成更合适的组件。

**Comment by hi94740** [comment]
最近的更新增加了高级筛选功能，高级筛选能保证显示所有的分组
